# Generated by Django 4.1.7 on 2023-06-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
