# Generated by Django 4.1.7 on 2023-10-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
