# Generated by Django 4.1.7 on 2023-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_customusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
