# Generated by Django 4.1.7 on 2023-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_customusers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customuser',
            field=models.ManyToManyField(to='posts.customusers'),
        ),
    ]
