# Generated by Django 4.1.7 on 2024-02-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_customusers_password_remove_customusers_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='password',
        ),
    ]
