# Generated by Django 4.1.7 on 2024-02-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_customusers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='posted',
        ),
        migrations.AddField(
            model_name='post',
            name='userposted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.customusers'),
        ),
    ]
