# Generated by Django 5.0.6 on 2024-10-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_customusers_posted_post_userposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
                ('user_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.customusers')),
            ],
        ),
    ]
