# Generated by Django 5.0.6 on 2024-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_customusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
